version: "3.8"
   
services:
  bookitaptdb:
    env_file: .env
    image: bitnami/postgresql:13
    volumes:
      - bookitaptdb:/var/lib/postgresql/data
    container_name: bookitaptdb
    ports:
      - 5432:5432

  web:
    build: .
    command: ./django-entrypoint.sh
    restart: unless-stopped
    volumes:
      - .:/src
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - bookitaptdb

volumes:
  bookitaptdb:
    external: false